# Use the official PostgreSQL image as the base image
FROM postgres:15.2-alpine

# Set environment variables (customize as needed)
ENV POSTGRES_DB=microsvc-db
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=postgres

# Optionally, expose the PostgreSQL port if needed (e.g., for local development)
EXPOSE 5432
